export const ProductData = [
        {
            id: 1,
            imgUrl: "https://img.freepik.com/free-vector/indian-rupee-money-bag_23-2148019023.jpg",
            name: "Personal Loan",
            category: "Personl Loan",
            commission_type: "VARIABLE",
            commission_value: "5%",
            label_tag: "Popular",
            status: "active",
        },{
            id: 2,
            imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDjR-wVIxYU7uwWxQFbLR6I7TxqHTmn23M0w&s",
            name: "Home Loan",
            category: "Home Loan",
            commission_type: "VARIABLE",
            commission_value: "0.7%",
            label_tag: "",
            status: "active",
        },{
            id: 3,
            imgUrl: "https://cdn4.vectorstock.com/i/1000x1000/36/83/handshake-sign-icon-successful-business-symbol-vector-2873683.jpg",
            name: "Business Loan",
            category: "Business Loan",
            commission_type: "VARIABLE",
            commission_value: "2%",
            label_tag: "",
            status: "active",
        },{
            id: 4,
            imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3OgkqBl4Y3NlLy3b1wAzc9usS_0pVKr_wLg&s",
            name: "Credit Card",
            category: "PCredit Card",
            commission_type: "FIXED",
            commission_value: "$500",
            label_tag: "",
            status: "active",
        },{
            id: 5,
            imgUrl: "https://cdn.vectorstock.com/i/1000v/10/15/creative-capital-letters-a-b-c-d-inscribed-vector-23661015.jpg",
            name: "ABCD app",
            category: "Application",
            commission_type: "Fixed",
            commission_value: "540",
            label_tag: "Earn more",
            status: "active",
        },{
            id: 6,
            imgUrl: "https://cbx-prod.b-cdn.net/COLOURBOX37031491.jpg?width=800&height=800&quality=70",
            name: "ABCD Test App",
            category: "Application",
            commission_type: "VARIABLE",
            commission_value: "5%",
            label_tag: "ABCD",
            status: "inactive",
        }
    ]